name: test
on: 
    push:
    pull_request:
      
jobs:
   first-job:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
          with:
             fetch-depth: 2
        - name: last modified file
          id: new
          run: |
               git diff --name-only --no-commit-id ${{ github.event.before }} ${{ github.sha }}
              #  git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} 
              #  echo "data=$test" >> "$GITHUB_OUTPUT" 
      
        
              